---
abstract: 'Mail::Toaster perl programs and modules'
author:
  - 'Matt Simerson (matt@tnpi.net)'
build_requires:
  Test::Simple: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mail-Toaster
no_index:
  directory:
    - t
    - inc
requires:
  DBI: 1
  Data::Dumper: 0
  Date::Parse: 1
  DateTime: 0.5
  Email::Valid: 0
  English: 0
  File::stat: 0
  Getopt::Long: 0
  IO::Socket::SSL: 0
  Mail::Send: 0
  Net::DNS: 0.2
  Params::Validate: 0.7
  Pod::Usage: 0
  Sys::Hostname: 0
  URI: 0
  perl: 5.008001
  version: 0
resources:
  bugtracker: https://github.com/msimerson/Mail-Toaster/issues
  homepage: https://github.com/msimerson/Mail-Toaster/
  repository: git@github.com:msimerson/Mail-Toaster.git
version: 5.42
